/**
 * Mapping of backend place type keys to Vietnamese display labels.
 * Use `translatePlaceType` to get a human-friendly label with fallback.
 */
export const TYPE_TRANSLATIONS: Record<string, string> = {
  adventure_sport_center: 'Trung tâm thể thao mạo hiểm',
  adventure_sports_center: 'Trung tâm thể thao mạo hiểm',
  amusement_center: 'Trung tâm giải trí',
  amusement_park: 'Công viên giải trí',
  apartment_building: 'Tòa nhà căn hộ',
  aquarium: 'Thủy cung',
  asian_restaurant: 'Nhà hàng Châu Á',
  bar: 'Quán bar',
  bar_and_grill: 'Quán bar & nướng',
  beach: 'Bãi biển',
  beach_resort: 'Khu nghỉ dưỡng bãi biển',
  botanical_garden: 'Vườn bách thảo',
  brunch_restaurant: 'Quán brunch',
  cafe: 'Quán cà phê',
  coffee_shop: 'Cửa hàng cà phê', // Khác biệt với cafe
  condominium_complex: 'Khu chung cư',
  corporate_office: 'Văn phòng công ty',
  cultural_center: 'Trung tâm văn hóa',
  cultural_landmark: 'Di tích/Địa danh văn hóa',
  concert_hall: 'Nhà hòa nhạc',
  conference_center: 'Trung tâm hội nghị',
  event_venue: 'Địa điểm tổ chức sự kiện',
  farm: 'Trang trại',
  ferris_wheel: 'Vòng đu quay',
  food: 'Ẩm thực',
  food_court: 'Khu ẩm thực',
  food_street: 'Phố ẩm thực',
  fast_food: 'Ăn nhanh',
  french_restaurant: 'Nhà hàng Pháp',
  garden: 'Vườn',
  golf_course: 'Sân golf',
  government_office: 'Cơ quan nhà nước',
  hiking_area: 'Khu vực đi bộ đường mòn',
  hiking_trail: 'Đường mòn đi bộ',
  hindu_temple: 'Đền Hindu',
  historical_site: 'Di tích lịch sử',
  historical_landmark: 'Địa danh lịch sử',
  historical_place: 'Địa điểm lịch sử',
  hotel: 'Khách sạn',
  indian_restaurant: 'Nhà hàng Ấn Độ',
  italian_restaurant: 'Nhà hàng Ý',
  korean_restaurant: 'Nhà hàng Hàn Quốc',
  landmark: 'Địa danh',
  library: 'Thư viện',
  lodging: 'Chỗ lưu trú',
  marina: 'Cảng du thuyền',
  market: 'Chợ',
  local_market: 'Chợ địa phương',
  museum: 'Bảo tàng',
  national_park: 'Vườn quốc gia',
  natural_feature: 'Danh thắng thiên nhiên',
  nature_reserve: 'Khu bảo tồn thiên nhiên',
  night_club: 'Câu lạc bộ đêm',
  night_market: 'Chợ đêm',
  nightlife: 'Cuộc sống về đêm',
  opera_house: 'Nhà hát opera',
  other: 'Khác',
  park: 'Công viên',
  performing_arts_theater: 'Nhà hát nghệ thuật biểu diễn',
  pizza_restaurant: 'Nhà hàng pizza',
  place_of_worship: 'Nơi thờ tự',
  playground: 'Sân chơi',
  point_of_interest: 'Điểm tham quan',
  private_guest_room: 'Phòng riêng cho khách',
  pub: 'Quán rượu',
  resort_hotel: 'Khách sạn nghỉ dưỡng',
  restaurant: 'Nhà hàng',
  sculpture: 'Tác phẩm điêu khắc',
  seafood_restaurant: 'Nhà hàng hải sản',
  seafood: 'Hải sản',
  spa: 'Spa',
  sports_activity_location: 'Địa điểm hoạt động thể thao',
  steak_house: 'Nhà hàng bít tết',
  store: 'Cửa hàng',
  thai_restaurant: 'Nhà hàng Thái',
  theater: 'Nhà hát',
  tour_agency: 'Công ty du lịch',
  tourist_attraction: 'Điểm thu hút khách du lịch',
  travel_agency: 'Đại lý du lịch',
  vegan_restaurant: 'Nhà hàng thuần chay',
  vietnamese_restaurant: 'Nhà hàng Việt Nam',
  visitor_center: 'Trung tâm thông tin du khách',
  viewpoint: 'Điểm ngắm',
  water_park: 'Công viên nước',
  waterfall: 'Thác nước',
  wildlife_refuge: 'Khu bảo tồn động vật hoang dã',
  zoo: 'Sở thú',
  river: 'Sông',
  lake: 'Hồ',
  shopping_mall: 'Trung tâm thương mại',
  shopping: 'Mua sắm',
  art_gallery: 'Phòng trưng bày nghệ thuật',
  monument: 'Tượng đài',
  observatory: 'Đài thiên văn',
  cultural_site: 'Địa điểm văn hóa',
  heritage_site: 'Di sản văn hóa',
  amphitheater: 'Đấu trường ngoài trời',
  bike_rental: 'Cho thuê xe đạp',
  ski_resort: 'Khu trượt tuyết',
  ferry_terminal: 'Cảng phà',
};

export function translatePlaceType(key?: string | null): string {
  if (!key) return '';
  const k = String(key).trim();
  if (!k) return '';
  if (TYPE_TRANSLATIONS[k]) return TYPE_TRANSLATIONS[k];

  // Fallback: convert snake_case or kebab-case to Title Case (best-effort)
  const normalized = k.replace(/[-_]+/g, ' ').toLowerCase();
  const words = normalized.split(' ').map(w => w ? (w.charAt(0).toUpperCase() + w.slice(1)) : '');
  return words.join(' ');
}

export default translatePlaceType;
