export const reviews = [
  {
    id: '1',
    userName: 'Nguyễn Văn A',
    location: 'Lenas Donau Hotel, Đà Nẵng',
    rating: 5,
    comment: 'Khách sạn rất đẹp và sạch sẽ, nhân viên phục vụ nhiệt tình. Tôi sẽ quay lại lần sau!',
    date: '2 ngày trước',
  },
  {
    id: '2',
    userName: 'Trần Thị B',
    location: 'Alpine Resort Hotel, Đà Lạt',
    rating: 4,
    comment: 'Vị trí thuận tiện, gần trung tâm. Phòng rộng rãi và thoải mái.',
    date: '1 tuần trước',
  },
  {
    id: '3',
    userName: 'Lê Minh C',
    location: 'Valley View Estate, Nha Trang',
    rating: 5,
    comment: 'Trải nghiệm tuyệt vời! Giá cả hợp lý, view đẹp. Highly recommended!',
    date: '2 tuần trước',
  },
  {
    id: '4',
    userName: 'Phạm Thu D',
    location: 'Lenas Donau Hotel, Đà Nẵng',
    rating: 4,
    comment: 'Dịch vụ tốt, đồ ăn ngon. Chỉ có điều wifi hơi yếu một chút.',
    date: '3 tuần trước',
  },
  {
    id: '5',
    userName: 'Hoàng Minh E',
    location: 'Beach Paradise Resort, Phú Quốc',
    rating: 5,
    comment: 'Resort sang trọng, view biển tuyệt đẹp. Bữa sáng buffet rất đa dạng và ngon. Nhân viên thân thiện và chuyên nghiệp.',
    date: '3 ngày trước',
  },
  {
    id: '6',
    userName: 'Đỗ Thị F',
    location: 'Mountain Lodge, Sa Pa',
    rating: 5,
    comment: 'Không gian yên tĩnh, không khí trong lành. View núi non hùng vĩ. Phòng ấm áp, thích hợp cho mùa đông.',
    date: '5 ngày trước',
  },
  {
    id: '7',
    userName: 'Vũ Công G',
    location: 'City Center Hotel, Hà Nội',
    rating: 4,
    comment: 'Vị trí trung tâm rất thuận tiện đi lại. Phòng sạch sẽ, giá cả hợp lý. Nhân viên lễ tân nhiệt tình hỗ trợ.',
    date: '1 tuần trước',
  },
  {
    id: '8',
    userName: 'Bùi Thị H',
    location: 'Riverside Hotel, Hội An',
    rating: 5,
    comment: 'Khách sạn nằm ngay bên sông Thu Bồn, view rất đẹp. Gần phố cổ chỉ 5 phút đi bộ. Nhân viên chu đáo, phục vụ tận tình.',
    date: '4 ngày trước',
  },
  {
    id: '9',
    userName: 'Ngô Văn I',
    location: 'Alpine Resort Hotel, Đà Lạt',
    rating: 5,
    comment: 'Không khí mát mẻ, view đồi thông tuyệt đẹp. Phòng ốc được trang trí theo phong cách châu Âu rất lãng mạn. Thích hợp cho cặp đôi.',
    date: '1 tuần trước',
  },
  {
    id: '10',
    userName: 'Đinh Thị K',
    location: 'Ocean View Resort, Vũng Tàu',
    rating: 4,
    comment: 'Resort view biển đẹp, hồ bơi rộng rãi. Bãi biển riêng sạch sẽ. Dịch vụ tốt nhưng giá hơi cao một chút.',
    date: '6 ngày trước',
  },
  {
    id: '11',
    userName: 'Lý Văn L',
    location: 'Valley View Estate, Nha Trang',
    rating: 5,
    comment: 'Căn hộ rất rộng rãi, view biển tuyệt đẹp. Có đầy đủ tiện nghi, bếp nấu ăn hiện đại. Phù hợp cho gia đình đông người.',
    date: '2 tuần trước',
  },
  {
    id: '12',
    userName: 'Mai Thị M',
    location: 'Boutique Hotel, TP.HCM',
    rating: 4,
    comment: 'Khách sạn boutique nhỏ xinh, thiết kế độc đáo. Nằm trong hẻm yên tĩnh nhưng vẫn gần trung tâm. Nhân viên thân thiện.',
    date: '3 ngày trước',
  },
];

export const featuredDestinations = [
  {
    id: '1',
    name: 'Lenas Donau Hotel',
    location: 'Donau Elegance',
    region: 'TYROLEAN ALPS',
    size: '34m²',
    distance: '1km to centre',
    guests: 2,
    duration: '10 days',
    amenities: ['1 king bed', 'Free wi-fi', 'TV'],
    price: '$80',
    reviews: '72k Reviews',
    rating: 4.8,
    image: require('../assets/images/test_address/anh-01-16859402497861207466047.png'),
  },
  {
    id: '2',
    name: 'Alpine Resort Hotel',
    location: 'Mountain Paradise',
    region: 'SWISS ALPS',
    size: '42m²',
    distance: '2km to centre',
    guests: 2,
    duration: '7 days',
    amenities: ['1 king bed', 'Free wi-fi', 'TV'],
    price: '$120',
    reviews: '45k Reviews',
    rating: 4.9,
    image: require('../assets/images/test_address/canh-dep-da-lat-1.png'),
  },
  {
    id: '3',
    name: 'Valley View Estate',
    location: 'Scenic Resort',
    region: 'VIETNAM COAST',
    size: '50m²',
    distance: '500m to beach',
    guests: 4,
    duration: '14 days',
    amenities: ['2 king beds', 'Free wi-fi', 'TV'],
    price: '₫2,200,000',
    reviews: '89k Reviews',
    rating: 4.7,
    image: require('../assets/images/test_address/cau-vang-ba-na-19072019-1.jpg'),
  },
];

export const categories = [
  { id: '1', name: 'Khách sạn', icon: 'hotel' },
  { id: '2', name: 'Nhà hàng', icon: 'restaurant' },
  { id: '3', name: 'Thuê xe', icon: 'car' },
  { id: '4', name: 'Voucher', icon: 'ticket' },
  { id: '5', name: 'Tour', icon: 'map-marker' },
  { id: '6', name: 'Vé máy bay', icon: 'plane' },
  { id: '7', name: 'Spa', icon: 'spa' },
  { id: '8', name: 'Sự kiện', icon: 'calendar' },
  { id: '9', name: 'Đặc sản', icon: 'gift' },
];

export const favoriteDestinations = [
  {
    id: 'f1',
    name: 'Seaside Breeze Hotel',
    location: 'Beachfront, Phú Quốc',
    region: 'VIETNAM COAST',
    size: '28m²',
    distance: '50m to beach',
    guests: 2,
    duration: '3 days',
    amenities: ['Sea view', 'Free wi-fi', 'Breakfast'],
    price: '₫1,200,000',
    reviews: '3.4k Reviews',
    rating: 4.6,
    image: require('../assets/images/test_address/anh-01-16859402497861207466047.png'),
  },
  {
    id: 'f2',
    name: 'Mountain Retreat Lodge',
    location: 'Highlands, Đà Lạt',
    region: 'HIGHLANDS',
    size: '40m²',
    distance: '2km to centre',
    guests: 2,
    duration: '5 days',
    amenities: ['Mountain view', 'Hot tub', 'Free wi-fi'],
    price: '₫1,800,000',
    reviews: '1.2k Reviews',
    rating: 4.8,
    image: require('../assets/images/test_address/canh-dep-da-lat-1.png'),
  },
  {
    id: 'f3',
    name: 'Golden Valley Resort',
    location: 'Nha Trang Bay',
    region: 'VIETNAM COAST',
    size: '55m²',
    distance: '300m to beach',
    guests: 4,
    duration: '7 days',
    amenities: ['Pool', 'Free breakfast', 'Parking'],
    price: '₫3,500,000',
    reviews: '5.6k Reviews',
    rating: 4.9,
    image: require('../assets/images/test_address/cau-vang-ba-na-19072019-1.jpg'),
  },
  {
    id: 'f4',
    name: 'City Center Boutique',
    location: 'Old Quarter, Hà Nội',
    region: 'URBAN',
    size: '30m²',
    distance: '500m to centre',
    guests: 2,
    duration: '2 days',
    amenities: ['Breakfast', 'AC', 'TV'],
    price: '₫900,000',
    reviews: '2.1k Reviews',
    rating: 4.3,
    image: require('../assets/images/test_address/anh-01-16859402497861207466047.png'),
  },
  {
    id: 'f5',
    name: 'Riverside Comfort Inn',
    location: 'Hoi An Riverside',
    region: 'RIVERSIDE',
    size: '36m²',
    distance: '100m to old town',
    guests: 3,
    duration: '4 days',
    amenities: ['River view', 'Bike rental', 'Free wi-fi'],
    price: '₫1,400,000',
    reviews: '4.0k Reviews',
    rating: 4.7,
    image: require('../assets/images/test_address/canh-dep-da-lat-1.png'),
  },
  {
    id: 'f6',
    name: 'Cozy Harbor Apartments',
    location: 'Da Nang Waterfront',
    region: 'COASTAL',
    size: '48m²',
    distance: '800m to centre',
    guests: 4,
    duration: '6 days',
    amenities: ['Kitchen', 'Balcony', 'Wi-fi'],
    price: '₫2,000,000',
    reviews: '900 Reviews',
    rating: 4.4,
    image: require('../assets/images/test_address/cau-vang-ba-na-19072019-1.jpg'),
  },
  {
    id: 'f7',
    name: 'Sunset View Hotel',
    location: 'Vũng Tàu Beach',
    region: 'BEACHFRONT',
    size: '32m²',
    distance: '10m to beach',
    guests: 2,
    duration: '3 days',
    amenities: ['Sea view', 'Breakfast included'],
    price: '₫1,300,000',
    reviews: '2.8k Reviews',
    rating: 4.5,
    image: require('../assets/images/test_address/anh-01-16859402497861207466047.png'),
  },
  {
    id: 'f8',
    name: 'Garden Villa Escape',
    location: 'Da Lat Countryside',
    region: 'COUNTRYSIDE',
    size: '60m²',
    distance: '5km to centre',
    guests: 4,
    duration: '8 days',
    amenities: ['Private garden', 'BBQ', 'Wi-fi'],
    price: '₫2,800,000',
    reviews: '600 Reviews',
    rating: 4.6,
    image: require('../assets/images/test_address/canh-dep-da-lat-1.png'),
  },
  {
    id: 'f9',
    name: 'Historic Townstay',
    location: 'Hoi An Old Town',
    region: 'HISTORIC',
    size: '22m²',
    distance: '50m to main street',
    guests: 2,
    duration: '2 days',
    amenities: ['Walking distance', 'Breakfast'],
    price: '₫800,000',
    reviews: '1.5k Reviews',
    rating: 4.2,
    image: require('../assets/images/test_address/cau-vang-ba-na-19072019-1.jpg'),
  },
  {
    id: 'f10',
    name: 'Blue Horizon Suites',
    location: 'Phu Quoc Island',
    region: 'ISLAND',
    size: '70m²',
    distance: '200m to beach',
    guests: 5,
    duration: '10 days',
    amenities: ['Pool', 'Kitchen', 'Sea view'],
    price: '₫4,500,000',
    reviews: '7.2k Reviews',
    rating: 4.9,
    image: require('../assets/images/test_address/anh-01-16859402497861207466047.png'),
  },
];
